# DO NOT EDIT THIS FILE!
#
# Python module FILTERWHEEL__POA generated by omniidl

import omniORB
omniORB.updateModule("FILTERWHEEL__POA")

# ** 1. Stub files contributing to this module
import FILTERWHEEL_idl

# ** 2. Sub-modules

# ** 3. End
