FilterWheel: FilterWheelBase Class Reference
FilterWheelBase Class Reference abstract
This class is automaticaly regenerated when devBuilder-gev is invoked, and therefore it should not be edited by the developer.
#include <FilterWheelBase.h>
Public Types
enum Filter {
UV, PURPLE, BLUE, GREEN,
YELLOW, ORANGE, RED, IR
}
The current Filter of the filter wheel.
Public Member Functions
FilterWheelBase (string name)
Device Constructor.
virtual ~FilterWheelBase ()
Destructor.
virtual void connect (string orbname, bool corbaDebug, unsigned threads, long priority, bool mode=Device::INTEGRATED, bool update=Device::DO_NOT_UPDATE)
Connects the device with a CORBA and other GCS Services.
virtual void start ()
Starting procedure.
virtual void init ()
Initialization procedure.
virtual void halt ()
Halting procedure.
virtual void shutdown ()
Shutdown procedure.
virtual void reset ()
Reset procedure.
virtual void restore ()
Restore procedure.
virtual void test ()
Test procedure.
virtual void abort ()
Stops all commands and goes to fault.
virtual char * report (short level)
Report device info.
const char * version ()
Reports device version.
virtual void moveCommand (FilterWheelBase::Filter position)=0
void command
virtual FilterWheelBase::Filter filterWheelFilter ()
FilterWheelFilter.
virtual bool filterWheelMoving ()
FilterWheelMoving.
Protected Member Functions
void createMonitors_ ()
Method to create monitors.
Protected Attributes
bool corbaDebug_
Activate/deactivate corba debugging.
bool update_
Activate/deactivate profile updating.
FilterWheelBase::Filter filterWheelFilter_
FilterWheelFilter.
bool filterWheelMoving_
FilterWheelMoving.
Detailed Description
This class is automaticaly regenerated when devBuilder-gev is invoked, and therefore it should not be edited by the developer.
Member Enumeration Documentation
enum FilterWheelBase::Filter
The current Filter of the filter wheel.
Enumerator
UV
PURPLE
BLUE
GREEN
YELLOW
ORANGE
RED
IR
Constructor & Destructor Documentation
FilterWheelBase::FilterWheelBase (string name)
Device Constructor.
References filterWheelMoving_.
FilterWheelBase::~FilterWheelBase () virtual
Destructor.
Member Function Documentation
void FilterWheelBase::connect (string orbname, bool corbaDebug, unsigned threads, long priority, bool mode = Device::INTEGRATED, bool update = Device::DO_NOT_UPDATE) virtual
Connects the device with a CORBA and other GCS Services.
Reimplemented in FilterWheel.
References corbaDebug_, and update_.
Referenced by FilterWheel::connect().
void FilterWheelBase::start () virtual
Starting procedure.
Reimplemented in FilterWheel.
References createMonitors_().
void FilterWheelBase::init () virtual
Initialization procedure.
Reimplemented in FilterWheel.
void FilterWheelBase::halt () virtual
Halting procedure.
Reimplemented in FilterWheel.
void FilterWheelBase::shutdown () virtual
Shutdown procedure.
Reimplemented in FilterWheel.
void FilterWheelBase::reset () virtual
Reset procedure.
Reimplemented in FilterWheel.
void FilterWheelBase::restore () virtual
Restore procedure.
void FilterWheelBase::test () virtual
Test procedure.
Reimplemented in FilterWheel.
void FilterWheelBase::abort () virtual
Stops all commands and goes to fault.
Reimplemented in FilterWheel.
char * FilterWheelBase::report (short level) virtual
Report device info.
Reimplemented in FilterWheel.
References filterWheelMoving().
Referenced by FilterWheel::report().
const char * FilterWheelBase::version ()
Reports device version.
virtual void FilterWheelBase::moveCommand (FilterWheelBase::Filter position) pure virtual
void command
Implemented in FilterWheel.
Referenced by FilterWheelAdapter::moveCommand().
FilterWheelBase::Filter FilterWheelBase::filterWheelFilter () virtual
FilterWheelFilter.
magnitude:
description:FilterWheelFilter
values:UV, PURPLE, BLUE, GREEN, YELLOW, ORANGE, RED, IR
sampling:1s
storage:600.0s
References filterWheelFilter_.
Referenced by FilterWheelAdapter::filterWheelFilter().
bool FilterWheelBase::filterWheelMoving () virtual
FilterWheelMoving.
magnitude:
description:FilterWheelMoving
maximum:true
minimum:false
units:None
sampling:0.2s
storage:60.0s
References filterWheelMoving_.
Referenced by FilterWheelAdapter::filterWheelMoving(), and report().
void FilterWheelBase::createMonitors_ () protected
Method to create monitors.
Referenced by FilterWheel::start(), and start().
Member Data Documentation
bool FilterWheelBase::corbaDebug_ protected
Activate/deactivate corba debugging.
Referenced by connect().
bool FilterWheelBase::update_ protected
Activate/deactivate profile updating.
Referenced by connect().
FilterWheelBase::Filter FilterWheelBase::filterWheelFilter_ protected
FilterWheelFilter.
Referenced by filterWheelFilter(), FilterWheel::init(), and FilterWheel::moveCommand().
bool FilterWheelBase::filterWheelMoving_ protected
FilterWheelMoving.
Referenced by FilterWheelBase(), filterWheelMoving(), and FilterWheel::moveCommand().
The documentation for this class was generated from the following files:
FilterWheelBase.h
FilterWheelBase.cpp