FilterWheel: FilterWheel Class Reference
FilterWheel Class Reference
#include <FilterWheel.h>
Public Member Functions
FilterWheel (string name)
Device Constructor.
virtual ~FilterWheel ()
Destructor.
void connect (string orbname, bool corbaDebug, unsigned threads, long priority, bool mode=Device::INTEGRATED, bool update=Device::DO_NOT_UPDATE)
Connects the device with a CORBA and other GCS Services.
void start ()
Starting procedure.
void init ()
Initialization procedure.
void halt ()
Halting procedure.
void shutdown ()
Shutdown procedure.
void reset ()
Reset procedure.
void test ()
Test procedure.
void abort ()
Stops all commands and goes to fault.
char * report (short level)
Report device info.
void moveCommand (FilterWheelBase::Filter position)
void command
Public Member Functions inherited from FilterWheelBase
FilterWheelBase (string name)
Device Constructor.
virtual ~FilterWheelBase ()
Destructor.
virtual void restore ()
Restore procedure.
const char * version ()
Reports device version.
virtual FilterWheelBase::Filter filterWheelFilter ()
FilterWheelFilter.
virtual bool filterWheelMoving ()
FilterWheelMoving.
Additional Inherited Members
Public Types inherited from FilterWheelBase
enum Filter {
UV, PURPLE, BLUE, GREEN,
YELLOW, ORANGE, RED, IR
}
The current Filter of the filter wheel.
Protected Member Functions inherited from FilterWheelBase
void createMonitors_ ()
Method to create monitors.
Protected Attributes inherited from FilterWheelBase
bool corbaDebug_
Activate/deactivate corba debugging.
bool update_
Activate/deactivate profile updating.
FilterWheelBase::Filter filterWheelFilter_
FilterWheelFilter.
bool filterWheelMoving_
FilterWheelMoving.
Constructor & Destructor Documentation
FilterWheel::FilterWheel (string name)
Device Constructor.
FilterWheel::~FilterWheel () virtual
Destructor.
Member Function Documentation
void FilterWheel::connect (string orbname, bool corbaDebug, unsigned threads, long priority, bool mode = Device::INTEGRATED, bool update = Device::DO_NOT_UPDATE) virtual
Connects the device with a CORBA and other GCS Services.
Reimplemented from FilterWheelBase.
References FilterWheelBase::connect().
void FilterWheel::start () virtual
Starting procedure.
Reimplemented from FilterWheelBase.
References FilterWheelBase::createMonitors_().
void FilterWheel::init () virtual
Initialization procedure.
Reimplemented from FilterWheelBase.
References FilterWheelBase::BLUE, and FilterWheelBase::filterWheelFilter_.
void FilterWheel::halt () virtual
Halting procedure.
Reimplemented from FilterWheelBase.
void FilterWheel::shutdown () virtual
Shutdown procedure.
Reimplemented from FilterWheelBase.
void FilterWheel::reset () virtual
Reset procedure.
Reimplemented from FilterWheelBase.
void FilterWheel::test () virtual
Test procedure.
Reimplemented from FilterWheelBase.
void FilterWheel::abort () virtual
Stops all commands and goes to fault.
Reimplemented from FilterWheelBase.
char * FilterWheel::report (short level) virtual
Report device info.
Reimplemented from FilterWheelBase.
References FilterWheelBase::report().
void FilterWheel::moveCommand (FilterWheelBase::Filter position) virtual
void command
Implements FilterWheelBase.
References FilterWheelBase::filterWheelFilter_, and FilterWheelBase::filterWheelMoving_.
The documentation for this class was generated from the following files:
FilterWheel.h
FilterWheel.cpp