FilterWheel: FilterWheelAdapter Class Reference
FilterWheelAdapter Class Reference
#include <FilterWheelAdapter.h>
Public Member Functions
FilterWheelAdapter (FilterWheelBase *device)
~FilterWheelAdapter ()
void moveCommand (const FILTERWHEEL::Filter position)
FILTERWHEEL::Filter filterWheelFilter ()
CORBA::Boolean filterWheelMoving ()
Constructor & Destructor Documentation
FilterWheelAdapter::FilterWheelAdapter (FilterWheelBase * device)
FilterWheelAdapter::~FilterWheelAdapter ()
Member Function Documentation
void FilterWheelAdapter::moveCommand (const FILTERWHEEL::Filter position)
References FilterWheelBase::moveCommand().
FILTERWHEEL::Filter FilterWheelAdapter::filterWheelFilter ()
References FilterWheelBase::filterWheelFilter().
CORBA::Boolean FilterWheelAdapter::filterWheelMoving ()
References FilterWheelBase::filterWheelMoving().
The documentation for this class was generated from the following files:
FilterWheelAdapter.h
FilterWheelAdapter.cpp