package IMAGEDETECTOR;


/**
* IMAGEDETECTOR/ImageDetector_ifceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IMAGEDETECTOR.idl
* Sunday, May 21, 2023 12:39:07 PM UTC
*/

public interface ImageDetector_ifceOperations  extends DCF.Device_ifceOperations
{

  // Specific ImageDetector operations
  void expose () throws DGT.GCSException;
  void setExposureTimeSeconds (double time) throws DGT.GCSException;

  // Monitorable attributes (device magnitudes)
  boolean idExposing ();
  double idExposureTimeLeft ();
} // interface ImageDetector_ifceOperations
