package IMAGEDETECTOR;


/**
* IMAGEDETECTOR/ImageDetector_ifce.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IMAGEDETECTOR.idl
* Friday, May 19, 2023 4:38:23 PM UTC
*/

public interface ImageDetector_ifce extends ImageDetector_ifceOperations, DCF.Device_ifce, org.omg.CORBA.portable.IDLEntity 
{
} // interface ImageDetector_ifce
