package IMAGEDETECTOR;


/**
* IMAGEDETECTOR/ImageDetector_ifceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IMAGEDETECTOR.idl
* Thursday, May 18, 2023 6:56:04 PM UTC
*/

public interface ImageDetector_ifceOperations  extends DCF.Device_ifceOperations
{

  // Specific ImageDetector operations
  void expose () throws DGT.GCSException;
  void setExposureTimeSeconds (double time) throws DGT.GCSException;

  // Monitorable attributes (device magnitudes)
  boolean idExposing ();
  boolean idExposureTimeLeft ();
} // interface ImageDetector_ifceOperations
