package IMAGEDETECTOR;

/**
* IMAGEDETECTOR/ImageDetector_ifceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IMAGEDETECTOR.idl
* Wednesday, May 31, 2023 6:01:43 PM UTC
*/

public final class ImageDetector_ifceHolder implements org.omg.CORBA.portable.Streamable
{
  public IMAGEDETECTOR.ImageDetector_ifce value = null;

  public ImageDetector_ifceHolder ()
  {
  }

  public ImageDetector_ifceHolder (IMAGEDETECTOR.ImageDetector_ifce initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IMAGEDETECTOR.ImageDetector_ifceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IMAGEDETECTOR.ImageDetector_ifceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IMAGEDETECTOR.ImageDetector_ifceHelper.type ();
  }

}
