// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:376


#include "IMAGEDETECTORC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "IMAGEDETECTORC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for IMAGEDETECTOR::ImageDetector_ifce.

IMAGEDETECTOR::ImageDetector_ifce_ptr
TAO::Objref_Traits<IMAGEDETECTOR::ImageDetector_ifce>::duplicate (
    IMAGEDETECTOR::ImageDetector_ifce_ptr p)
{
  return IMAGEDETECTOR::ImageDetector_ifce::_duplicate (p);
}

void
TAO::Objref_Traits<IMAGEDETECTOR::ImageDetector_ifce>::release (
    IMAGEDETECTOR::ImageDetector_ifce_ptr p)
{
  ::CORBA::release (p);
}

IMAGEDETECTOR::ImageDetector_ifce_ptr
TAO::Objref_Traits<IMAGEDETECTOR::ImageDetector_ifce>::nil (void)
{
  return IMAGEDETECTOR::ImageDetector_ifce::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<IMAGEDETECTOR::ImageDetector_ifce>::marshal (
    const IMAGEDETECTOR::ImageDetector_ifce_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

void
IMAGEDETECTOR::ImageDetector_ifce::expose (
  void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };

  static TAO::Exception_Data
  _tao_IMAGEDETECTOR_ImageDetector_ifce_expose_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , DGT::_tc_GCSException
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "expose",
      6,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
    );

  _tao_call.invoke (
      _tao_IMAGEDETECTOR_ImageDetector_ifce_expose_exceptiondata,
      1
    );
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

void
IMAGEDETECTOR::ImageDetector_ifce::setExposureTimeSeconds (
  ::CORBA::Double time)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Double>::in_arg_val _tao_time (time);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_time
    };

  static TAO::Exception_Data
  _tao_IMAGEDETECTOR_ImageDetector_ifce_setExposureTimeSeconds_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , DGT::_tc_GCSException
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setExposureTimeSeconds",
      22,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
    );

  _tao_call.invoke (
      _tao_IMAGEDETECTOR_ImageDetector_ifce_setExposureTimeSeconds_exceptiondata,
      1
    );
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

::CORBA::Boolean
IMAGEDETECTOR::ImageDetector_ifce::idExposing (
  void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::ACE_InputCDR::to_boolean>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_idExposing",
      15,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
    );

  _tao_call.invoke (0, 0);

  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

::CORBA::Double
IMAGEDETECTOR::ImageDetector_ifce::idExposureTimeLeft (
  void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::CORBA::Double>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_idExposureTimeLeft",
      23,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
    );

  _tao_call.invoke (0, 0);

  return _tao_retval.retn ();
}

IMAGEDETECTOR::ImageDetector_ifce::ImageDetector_ifce (void)
{
}

IMAGEDETECTOR::ImageDetector_ifce::~ImageDetector_ifce (void)
{
}

void
IMAGEDETECTOR::ImageDetector_ifce::_tao_any_destructor (void *_tao_void_pointer)
{
  ImageDetector_ifce *_tao_tmp_pointer =
    static_cast<ImageDetector_ifce *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

IMAGEDETECTOR::ImageDetector_ifce_ptr
IMAGEDETECTOR::ImageDetector_ifce::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<ImageDetector_ifce>::narrow (
        _tao_objref,
        "IDL:gtc/IMAGEDETECTOR/ImageDetector_ifce:1.0");
}

IMAGEDETECTOR::ImageDetector_ifce_ptr
IMAGEDETECTOR::ImageDetector_ifce::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<ImageDetector_ifce>::unchecked_narrow (
        _tao_objref);
}

IMAGEDETECTOR::ImageDetector_ifce_ptr
IMAGEDETECTOR::ImageDetector_ifce::_nil (void)
{
  return 0;
}

IMAGEDETECTOR::ImageDetector_ifce_ptr
IMAGEDETECTOR::ImageDetector_ifce::_duplicate (ImageDetector_ifce_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
IMAGEDETECTOR::ImageDetector_ifce::_tao_release (ImageDetector_ifce_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
IMAGEDETECTOR::ImageDetector_ifce::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:gtc/MM/Monitor_ifce:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:gtc/DCF/Device_ifce:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:gtc/IMAGEDETECTOR/ImageDetector_ifce:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* IMAGEDETECTOR::ImageDetector_ifce::_interface_repository_id (void) const
{
  return "IDL:gtc/IMAGEDETECTOR/ImageDetector_ifce:1.0";
}

::CORBA::Boolean
IMAGEDETECTOR::ImageDetector_ifce::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:72

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_IMAGEDETECTOR_ImageDetector_ifce (
    ::CORBA::tk_objref,
    "IDL:gtc/IMAGEDETECTOR/ImageDetector_ifce:1.0",
    "ImageDetector_ifce");
  

namespace IMAGEDETECTOR
{
  ::CORBA::TypeCode_ptr const _tc_ImageDetector_ifce =
    &_tao_tc_IMAGEDETECTOR_ImageDetector_ifce;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:41
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<IMAGEDETECTOR::ImageDetector_ifce>::to_object (
      ::CORBA::Object_ptr &_tao_elem) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace IMAGEDETECTOR
{
  

  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      ImageDetector_ifce_ptr _tao_elem)
  {
    ImageDetector_ifce_ptr _tao_objptr =
      ImageDetector_ifce::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }

  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      ImageDetector_ifce_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<ImageDetector_ifce>::insert (
        _tao_any,
        ImageDetector_ifce::_tao_any_destructor,
        _tc_ImageDetector_ifce,
        *_tao_elem);
  }

  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      ImageDetector_ifce_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<ImageDetector_ifce>::extract (
          _tao_any,
          ImageDetector_ifce::_tao_any_destructor,
          _tc_ImageDetector_ifce,
          _tao_elem);
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    IMAGEDETECTOR::ImageDetector_ifce_ptr _tao_elem)
{
  IMAGEDETECTOR::ImageDetector_ifce_ptr _tao_objptr =
    IMAGEDETECTOR::ImageDetector_ifce::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    IMAGEDETECTOR::ImageDetector_ifce_ptr *_tao_elem)
{
  TAO::Any_Impl_T<IMAGEDETECTOR::ImageDetector_ifce>::insert (
      _tao_any,
      IMAGEDETECTOR::ImageDetector_ifce::_tao_any_destructor,
      IMAGEDETECTOR::_tc_ImageDetector_ifce,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    IMAGEDETECTOR::ImageDetector_ifce_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<IMAGEDETECTOR::ImageDetector_ifce>::extract (
        _tao_any,
        IMAGEDETECTOR::ImageDetector_ifce::_tao_any_destructor,
        IMAGEDETECTOR::_tc_ImageDetector_ifce,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:54

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const IMAGEDETECTOR::ImageDetector_ifce_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    IMAGEDETECTOR::ImageDetector_ifce_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::IMAGEDETECTOR::ImageDetector_ifce RHS_SCOPED_NAME;

  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (obj.in ());
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



