types:
    idls:
        - >
            struct DoubleValue
            {
                string componentName;
                string magnitudeName;
                long long time_stamp;
                double value;
            };
           
systems:
    dds: { type: fastdds }
    ros2: { type: ros2 }
 
routes:
    dds_to_ros2: { from: dds, to: ros2 }

topics:
    OE.ObservingEngine.currentRA:
        type: "DoubleValue"
        route: dds_to_ros2