ImageDetector: ImageDetector Class Reference
ImageDetector Class Reference
#include <ImageDetector.h>
Public Member Functions
ImageDetector (string name)
Device Constructor.
virtual ~ImageDetector ()
Destructor.
void connect (string orbname, bool corbaDebug, unsigned threads, long priority, bool mode=Device::INTEGRATED, bool update=Device::DO_NOT_UPDATE)
Connects the device with a CORBA and other GCS Services.
void start ()
Starting procedure.
void init ()
Initialization procedure.
void halt ()
Halting procedure.
void shutdown ()
Shutdown procedure.
void reset ()
Reset procedure.
void test ()
Test procedure.
void abort ()
Stops all commands and goes to fault.
char * report (short level)
Report device info.
void expose ()
Expose.
void setExposureTimeSeconds (double time)
Set exposure time in seconds.
Public Member Functions inherited from ImageDetectorBase
ImageDetectorBase (string name)
Device Constructor.
virtual ~ImageDetectorBase ()
Destructor.
virtual void restore ()
Restore procedure.
const char * version ()
Reports device version.
virtual bool idExposing ()
ImageDetectorExposing.
virtual double idExposureTimeLeft ()
ImageDetectorExposureTimeLeft.
Protected Attributes
double numberOfExposures_
double exposureTimeSeconds_
bool abortAcquisition_
ShortArray2D windows_
Protected Attributes inherited from ImageDetectorBase
bool corbaDebug_
Activate/deactivate corba debugging.
bool update_
Activate/deactivate profile updating.
bool idExposing_
ImageDetectorExposing.
double idExposureTimeLeft_
ImageDetectorExposureTimeLeft.
Additional Inherited Members
Protected Member Functions inherited from ImageDetectorBase
void createMonitors_ ()
Method to create monitors.
Constructor & Destructor Documentation
ImageDetector::ImageDetector (string name)
Device Constructor.
References windows_.
ImageDetector::~ImageDetector () virtual
Destructor.
Member Function Documentation
void ImageDetector::connect (string orbname, bool corbaDebug, unsigned threads, long priority, bool mode = Device::INTEGRATED, bool update = Device::DO_NOT_UPDATE) virtual
Connects the device with a CORBA and other GCS Services.
Reimplemented from ImageDetectorBase.
References ImageDetectorBase::connect().
void ImageDetector::start () virtual
Starting procedure.
Reimplemented from ImageDetectorBase.
References ImageDetectorBase::createMonitors_().
void ImageDetector::init () virtual
Initialization procedure.
Reimplemented from ImageDetectorBase.
References FrameAgent::connect(), and exposureTimeSeconds_.
void ImageDetector::halt () virtual
Halting procedure.
Reimplemented from ImageDetectorBase.
void ImageDetector::shutdown () virtual
Shutdown procedure.
Reimplemented from ImageDetectorBase.
void ImageDetector::reset () virtual
Reset procedure.
Reimplemented from ImageDetectorBase.
void ImageDetector::test () virtual
Test procedure.
Reimplemented from ImageDetectorBase.
void ImageDetector::abort () virtual
Stops all commands and goes to fault.
Reimplemented from ImageDetectorBase.
char * ImageDetector::report (short level) virtual
Report device info.
Reimplemented from ImageDetectorBase.
References ImageDetectorBase::report().
void ImageDetector::expose () virtual
Expose.
Implements ImageDetectorBase.
References exposureTimeSeconds_, ImageDetectorBase::idExposing_, ImageDetectorBase::idExposureTimeLeft_, FrameAgent::sendFrame(), and windows_.
void ImageDetector::setExposureTimeSeconds (double time) virtual
Set exposure time in seconds.
Implements ImageDetectorBase.
References exposureTimeSeconds_.
Member Data Documentation
double ImageDetector::numberOfExposures_ protected
double ImageDetector::exposureTimeSeconds_ protected
Referenced by expose(), init(), and setExposureTimeSeconds().
bool ImageDetector::abortAcquisition_ protected
ShortArray2D ImageDetector::windows_ protected
Referenced by expose(), and ImageDetector().
The documentation for this class was generated from the following files:
ImageDetector.h
ImageDetector.cpp