ImageDetector: FrameAgent Class Reference
FrameAgent Class Reference
#include <FrameAgent.h>
Public Member Functions
FrameAgent (string name, string dfAgentName)
Device Constructor.
virtual ~FrameAgent ()
Destructor.
void connect (LogAgent *logAgent, AlarmAgent *alarmAgent, std::string dataFactoryAgentInstanceCorbaName, std::string dataFactoryManagerInstanceCorbaName)
Connects the DF components - DFAgent and DFManager.
void disconnect ()
Disconnects the DF components - DFAgent and DFManager.
void sendFrame (const Frame< double, 2 > &frame, double exposureTimeSeconds, ShortArray2D windows)
sendFrame
void sendFitsFile (string fitsFilename, double exposureTimeSeconds, ShortArray2D windows)
sendFitsFile
Constructor & Destructor Documentation
FrameAgent::FrameAgent (string name, string dfAgentName)
Device Constructor.
FrameAgent::~FrameAgent () virtual
Destructor.
Member Function Documentation
void FrameAgent::connect (LogAgent * logAgent, AlarmAgent * alarmAgent, std::string dataFactoryAgentInstanceCorbaName, std::string dataFactoryManagerInstanceCorbaName)
Connects the DF components - DFAgent and DFManager.
Referenced by ImageDetector::init().
void FrameAgent::disconnect ()
Disconnects the DF components - DFAgent and DFManager.
void FrameAgent::sendFrame (const Frame< double, 2 > & frame, double exposureTimeSeconds, ShortArray2D windows)
sendFrame
Referenced by ImageDetector::expose(), and sendFitsFile().
void FrameAgent::sendFitsFile (string fitsFilename, double exposureTimeSeconds, ShortArray2D windows)
sendFitsFile
References sendFrame().
The documentation for this class was generated from the following files:
FrameAgent.h
FrameAgent.cpp