ImageDetector: ImageDetectorAdapter Class Reference
ImageDetectorAdapter Class Reference
#include <ImageDetectorAdapter.h>
Public Member Functions
ImageDetectorAdapter (ImageDetectorBase *device)
~ImageDetectorAdapter ()
void expose ()
void setExposureTimeSeconds (CORBA::Double time)
CORBA::Boolean idExposing ()
CORBA::Boolean idExposureTimeLeft ()
Constructor & Destructor Documentation
ImageDetectorAdapter::ImageDetectorAdapter (ImageDetectorBase * device)
ImageDetectorAdapter::~ImageDetectorAdapter ()
Member Function Documentation
void ImageDetectorAdapter::expose ()
References ImageDetectorBase::expose().
void ImageDetectorAdapter::setExposureTimeSeconds (CORBA::Double time)
References ImageDetectorBase::setExposureTimeSeconds().
CORBA::Boolean ImageDetectorAdapter::idExposing ()
References ImageDetectorBase::idExposing().
CORBA::Boolean ImageDetectorAdapter::idExposureTimeLeft ()
References ImageDetectorBase::idExposureTimeLeft().
The documentation for this class was generated from the following files:
ImageDetectorAdapter.h
ImageDetectorAdapter.cpp