ImageDetector: ImageDetectorBase Class Reference
ImageDetectorBase Class Reference abstract
This class is automaticaly regenerated when devBuilder-gev is invoked, and therefore it should not be edited by the developer.
#include <ImageDetectorBase.h>
Public Member Functions
ImageDetectorBase (string name)
Device Constructor.
virtual ~ImageDetectorBase ()
Destructor.
virtual void connect (string orbname, bool corbaDebug, unsigned threads, long priority, bool mode=Device::INTEGRATED, bool update=Device::DO_NOT_UPDATE)
Connects the device with a CORBA and other GCS Services.
virtual void start ()
Starting procedure.
virtual void init ()
Initialization procedure.
virtual void halt ()
Halting procedure.
virtual void shutdown ()
Shutdown procedure.
virtual void reset ()
Reset procedure.
virtual void restore ()
Restore procedure.
virtual void test ()
Test procedure.
virtual void abort ()
Stops all commands and goes to fault.
virtual char * report (short level)
Report device info.
const char * version ()
Reports device version.
virtual void expose ()=0
Expose.
virtual void setExposureTimeSeconds (double time)=0
Set exposure time in seconds.
virtual bool idExposing ()
ImageDetectorExposing.
virtual double idExposureTimeLeft ()
ImageDetectorExposureTimeLeft.
Protected Member Functions
void createMonitors_ ()
Method to create monitors.
Protected Attributes
bool corbaDebug_
Activate/deactivate corba debugging.
bool update_
Activate/deactivate profile updating.
bool idExposing_
ImageDetectorExposing.
double idExposureTimeLeft_
ImageDetectorExposureTimeLeft.
Detailed Description
This class is automaticaly regenerated when devBuilder-gev is invoked, and therefore it should not be edited by the developer.
Constructor & Destructor Documentation
ImageDetectorBase::ImageDetectorBase (string name)
Device Constructor.
References idExposing_, and idExposureTimeLeft_.
Referenced by createMonitors_().
ImageDetectorBase::~ImageDetectorBase () virtual
Destructor.
Member Function Documentation
void ImageDetectorBase::connect (string orbname, bool corbaDebug, unsigned threads, long priority, bool mode = Device::INTEGRATED, bool update = Device::DO_NOT_UPDATE) virtual
Connects the device with a CORBA and other GCS Services.
Reimplemented in ImageDetector.
References corbaDebug_, and update_.
Referenced by ImageDetector::connect().
void ImageDetectorBase::start () virtual
Starting procedure.
Reimplemented in ImageDetector.
References createMonitors_().
void ImageDetectorBase::init () virtual
Initialization procedure.
Reimplemented in ImageDetector.
void ImageDetectorBase::halt () virtual
Halting procedure.
Reimplemented in ImageDetector.
void ImageDetectorBase::shutdown () virtual
Shutdown procedure.
Reimplemented in ImageDetector.
void ImageDetectorBase::reset () virtual
Reset procedure.
Reimplemented in ImageDetector.
void ImageDetectorBase::restore () virtual
Restore procedure.
void ImageDetectorBase::test () virtual
Test procedure.
Reimplemented in ImageDetector.
void ImageDetectorBase::abort () virtual
Stops all commands and goes to fault.
Reimplemented in ImageDetector.
char * ImageDetectorBase::report (short level) virtual
Report device info.
Reimplemented in ImageDetector.
References idExposing(), and idExposureTimeLeft().
Referenced by ImageDetector::report().
const char * ImageDetectorBase::version ()
Reports device version.
virtual void ImageDetectorBase::expose () pure virtual
Expose.
Implemented in ImageDetector.
Referenced by ImageDetectorAdapter::expose().
virtual void ImageDetectorBase::setExposureTimeSeconds (double time) pure virtual
Set exposure time in seconds.
Implemented in ImageDetector.
Referenced by ImageDetectorAdapter::setExposureTimeSeconds().
bool ImageDetectorBase::idExposing () virtual
ImageDetectorExposing.
magnitude:
description:ImageDetectorExposing
maximum:true
minimum:false
units:None
sampling:100s
storage:600s
References idExposing_.
Referenced by ImageDetectorAdapter::idExposing(), and report().
double ImageDetectorBase::idExposureTimeLeft () virtual
ImageDetectorExposureTimeLeft.
magnitude:
description:ImageDetectorExposureTimeLeft
maximum:100000
minimum:0
units:Second
sampling:2s
storage:60.0s
References idExposureTimeLeft_.
Referenced by createMonitors_(), ImageDetectorAdapter::idExposureTimeLeft(), and report().
void ImageDetectorBase::createMonitors_ () protected
Method to create monitors.
References idExposureTimeLeft(), and ImageDetectorBase().
Referenced by ImageDetector::start(), and start().
Member Data Documentation
bool ImageDetectorBase::corbaDebug_ protected
Activate/deactivate corba debugging.
Referenced by connect().
bool ImageDetectorBase::update_ protected
Activate/deactivate profile updating.
Referenced by connect().
bool ImageDetectorBase::idExposing_ protected
ImageDetectorExposing.
Referenced by ImageDetector::expose(), idExposing(), and ImageDetectorBase().
double ImageDetectorBase::idExposureTimeLeft_ protected
ImageDetectorExposureTimeLeft.
Referenced by ImageDetector::expose(), idExposureTimeLeft(), and ImageDetectorBase().
The documentation for this class was generated from the following files:
ImageDetectorBase.h
ImageDetectorBase.cpp