package FILTERWHEEL;

/**
* FILTERWHEEL/FilterWheel_ifceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FILTERWHEEL.idl
* Sunday, May 21, 2023 3:43:39 PM UTC
*/

public final class FilterWheel_ifceHolder implements org.omg.CORBA.portable.Streamable
{
  public FILTERWHEEL.FilterWheel_ifce value = null;

  public FilterWheel_ifceHolder ()
  {
  }

  public FilterWheel_ifceHolder (FILTERWHEEL.FilterWheel_ifce initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FILTERWHEEL.FilterWheel_ifceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FILTERWHEEL.FilterWheel_ifceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FILTERWHEEL.FilterWheel_ifceHelper.type ();
  }

}
