package FILTERWHEEL;


/**
* FILTERWHEEL/FilterWheel_ifce.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FILTERWHEEL.idl
* Thursday, May 18, 2023 2:56:53 PM UTC
*/

public interface FilterWheel_ifce extends FilterWheel_ifceOperations, DCF.Device_ifce, org.omg.CORBA.portable.IDLEntity 
{
} // interface FilterWheel_ifce
