package FILTERWHEEL;


/**
* FILTERWHEEL/Filter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FILTERWHEEL.idl
* Sunday, May 21, 2023 3:43:39 PM UTC
*/

public class Filter implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 8;
  private static FILTERWHEEL.Filter[] __array = new FILTERWHEEL.Filter [__size];

  public static final int _UV = 0;
  public static final FILTERWHEEL.Filter UV = new FILTERWHEEL.Filter(_UV);
  public static final int _PURPLE = 1;
  public static final FILTERWHEEL.Filter PURPLE = new FILTERWHEEL.Filter(_PURPLE);
  public static final int _BLUE = 2;
  public static final FILTERWHEEL.Filter BLUE = new FILTERWHEEL.Filter(_BLUE);
  public static final int _GREEN = 3;
  public static final FILTERWHEEL.Filter GREEN = new FILTERWHEEL.Filter(_GREEN);
  public static final int _YELLOW = 4;
  public static final FILTERWHEEL.Filter YELLOW = new FILTERWHEEL.Filter(_YELLOW);
  public static final int _ORANGE = 5;
  public static final FILTERWHEEL.Filter ORANGE = new FILTERWHEEL.Filter(_ORANGE);
  public static final int _RED = 6;
  public static final FILTERWHEEL.Filter RED = new FILTERWHEEL.Filter(_RED);
  public static final int _IR = 7;
  public static final FILTERWHEEL.Filter IR = new FILTERWHEEL.Filter(_IR);

  public int value ()
  {
    return __value;
  }

  public static FILTERWHEEL.Filter from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Filter (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Filter
