package FILTERWHEEL;


/**
* FILTERWHEEL/FilterWheel_ifceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FILTERWHEEL.idl
* Thursday, May 18, 2023 2:56:53 PM UTC
*/

public interface FilterWheel_ifceOperations  extends DCF.Device_ifceOperations
{

  // Specific FilterWheel operations
  void moveCommand (short position) throws DGT.GCSException;

  // Monitorable attributes (device magnitudes)
  short filterWheelFilter ();
  boolean filterWheelMoving ();
} // interface FilterWheel_ifceOperations
