package FILTERWHEEL;


/**
* FILTERWHEEL/FilterWheel_ifceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FILTERWHEEL.idl
* Thursday, May 18, 2023 2:56:53 PM UTC
*/

abstract public class FilterWheel_ifceHelper
{
  private static String  _id = "IDL:gtc/FILTERWHEEL/FilterWheel_ifce:1.0";

  public static void insert (org.omg.CORBA.Any a, FILTERWHEEL.FilterWheel_ifce that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FILTERWHEEL.FilterWheel_ifce extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FILTERWHEEL.FilterWheel_ifceHelper.id (), "FilterWheel_ifce");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FILTERWHEEL.FilterWheel_ifce read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FilterWheel_ifceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FILTERWHEEL.FilterWheel_ifce value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FILTERWHEEL.FilterWheel_ifce narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FILTERWHEEL.FilterWheel_ifce)
      return (FILTERWHEEL.FilterWheel_ifce)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FILTERWHEEL._FilterWheel_ifceStub stub = new FILTERWHEEL._FilterWheel_ifceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FILTERWHEEL.FilterWheel_ifce unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FILTERWHEEL.FilterWheel_ifce)
      return (FILTERWHEEL.FilterWheel_ifce)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FILTERWHEEL._FilterWheel_ifceStub stub = new FILTERWHEEL._FilterWheel_ifceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
