package FILTERWHEEL;


/**
* FILTERWHEEL/FilterWheel_ifceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FILTERWHEEL.idl
* Sunday, May 21, 2023 3:43:39 PM UTC
*/

public interface FilterWheel_ifceOperations  extends DCF.Device_ifceOperations
{

  // Specific FilterWheel operations
  void moveCommand (FILTERWHEEL.Filter position) throws DGT.GCSException;

  // Monitorable attributes (device magnitudes)
  FILTERWHEEL.Filter filterWheelFilter ();
  boolean filterWheelMoving ();
} // interface FilterWheel_ifceOperations
