# DO NOT EDIT THIS FILE!
#
# Python module FILTERWHEEL generated by omniidl

import omniORB
omniORB.updateModule("FILTERWHEEL")

# ** 1. Stub files contributing to this module
import FILTERWHEEL_idl

# ** 2. Sub-modules

# ** 3. End
