# DO NOT EDIT THIS FILE!
#
# Python module IMAGEDETECTOR generated by omniidl

import omniORB
omniORB.updateModule("IMAGEDETECTOR")

# ** 1. Stub files contributing to this module
import IMAGEDETECTOR_idl

# ** 2. Sub-modules

# ** 3. End
